fiddler-labs/fiddler-samples

- content_root/tutorial/03 How to debug model upload.ipynb
> upload tutorial

- content_root/tutorial/01a Model monitoring with surrogate explanation.ipynb
- content_root/tutorial/09 Importing model hosted on Sagemaker.ipynb
- requirements.txt
- Added `fiddler-client` to `requirements.txt`
- Removed hard-code of client in Notebook 01a
- Added `pandas` import before call in Notebook 09
> Updated requirements, minor changes in 01a and 09

- README.md
- content_root/tutorial/00 Setup.ipynb
- content_root/tutorial/fiddler.ini
Added picture to main README, updated some wordings in README, fixed/added some links to tutorial section in README, removed default AUTH_TOKEN from setup sections
> Updates to docs

- content_root/tutorial/upload-model-containers.ipynb
There was some stale comments in the examples and making the comments a
little bit better.
> update the comments based on the anthem call

- README.md
Added image to repo in last PR, fixed path to this on README
> Quick fix for image path in README

- content_root/tutorial/01 Basic model monitoring.ipynb
- content_root/tutorial/01a Model monitoring with surrogate explanation.ipynb
- content_root/tutorial/06 publish_event.ipynb
Add code to trigger model predictions before sending the events.
> trigger predictions before sending events

- content_root/tutorial/Quick Start.ipynb
Clarified the modifications we're making to the dataset within the quickstart.
"""
Note: In the next cell, we will be making some modifications to the field names of this dataset to better fit model training in later steps. We will also be adding a decisions column to our dataset. In total, we will be:
- Renaming field State to Location State (State is a reserved word for models, so this change was required for model training)
- Renaming columns to be a more library-friendly schema (lowercase and replacing spaces with underscores)
- Addition of a new high_value field to act as our decision column
"""
> Adding clarification on dataset modifications

- content_root/samples/datasets/auto_insurance/event_log.csv
- content_root/tutorial/Quick Start.ipynb
Add Imports section to quick start
Expand events count for monitoring from 100 to 5000 events
> QuickStart Add Imports section

- content_root/tutorial/00 Install & Setup.ipynb
Update the fiddler-client version
> Update 00 Install & Setup.ipynb

- content_root/tutorial/01a Monitoring Quickstart.ipynb
Removed Fiddler import at the beginning.
> Update 01a Monitoring Quickstart.ipynb

- content_root/samples/datasets/winequality/events.log
- content_root/tutorial/01b Monitoring With Your Model.ipynb
- content_root/tutorial/02a Sklearn Tabular Model.ipynb
**01b**
* Changed eventlog column name to match already existing dataset column in fiddler client. (`pH`) (content_root/samples/datasets/winequality/events.log)
* Updated `project_id` and `model_id` to matching with the pre-existing project in the fiddler client
* Removed deprecated `publish_events_log`. Using `publish_events_batch` instead.
**02a**
*  Changed `read_csv` input file string.
> Resolved issues and updated 01b and 02a tutorial notebooks

- content_root/tutorial/01b Monitoring With Your Model.ipynb
Fixed the project_id and removed API that are not supported
> Update 01b Monitoring With Your Model.ipynb

- content_root/tutorial/02a Sklearn Tabular Model.ipynb
update project_id to be consistent
> Update 02a Sklearn Tabular Model.ipynb

- content_root/tutorial/02c Tensorflow Text Model.ipynb
> Update 02c Tensorflow Text Model.ipynb

- content_root/tutorial/02b Tensorflow Tabular Model.ipynb
- content_root/tutorial/02c Tensorflow Text Model.ipynb
IQT customer was trying to upload these models and running into issue:
- 02b Tensorflow Tabular Model.ipynb - This model uses old upload_model_custom API -> updated to old upload_model_package
- 02c Tensorflow Text Model.ipynb - This model uploads and run predict and explanation from notebook. However, it fails explanation from UI because the output columnn in the package.py didn't match the model_info. Updated package.py
> Update tf examples

- content_root/tutorial/01a Monitoring Quickstart.ipynb
Argument `event_time_stamp` has been renamed `event_timestamp`. Updating quickstart.
> Update argument publish_event

- content_root/tutorial/business-use-cases/class-imbalance/class_weighted_drift.ipynb
Adding an example to show-case class-weighted drift for use-cases with class-imbalance
click here to view the notebook: https://github.com/fiddler-labs/fiddler-samples/blob/feature/class-imbalance/content_root/tutorial/business-use-cases/class-imbalance/class_weighted_drift.ipynb
> Example to show-case class-weighted drift

- content_root/tutorial/quickstart/Fiddler_QuickStart_NLP_Monitoring.ipynb
Made a few minor modifications to sample notebook
> updates to nlp example notebook

- content_root/tutorial/quickstart/Fiddler_Quick_Start_Simple_Monitoring.ipynb
1. remove python-client version
3. register_model to add_model
4. remove get_alerts, get_trigerred_alerts, and delete_alerts calls
> Fiddler_Quick_Start_Guide bug fixes + improvements

- content_root/tutorial/quickstart/Fiddler_Quick_Start_Simple_Monitoring.ipynb
Added a link to the NLP Notebook guide at the end.
> added links to the next guide at the end

- content_root/tutorial/quickstart/.ipynb_checkpoints/Fiddler_Quick_Start_Simple_Monitoring-checkpoint.ipynb
- content_root/tutorial/quickstart/Fiddler_Quick_Start_Simple_Monitoring.ipynb
self service docs requires 5-10 minutes text change instead of 3-5
> self service update
